pipeline {
    
    agent any

    tools {
        go '1.18.1'
    }
    
    stages {

        stage ('Clone') {
            steps {
                git branch: 'main', url: "https://github.com/22sujata8d/jenkins-ci-demo.git"
            }
        }

        stage("build") {

            steps {
                echo 'building the application...'
                sh 'ls'
                sh 'cd Cart/cmd/server'
                sh 'pwd'
                sh 'go build .'
            }
        }

        stage("test") {

            steps {
                echo 'testing the application...'
                sh 'go test -v ./...'
            }
        }

        stage("deploy") {

            steps {
                echo 'deploying the application...'
            }
        }
    }
}