pipeline {
    
    agent any

    stages {

        stage("build") {

            steps {
                echo 'building the application...'
                go build .
            }
        }

        stage("test") {

            steps {
                echo 'testing the application...'
                go test -v ./...
            }
        }

        stage("deploy") {

            steps {
                echo 'deploying the application...'
            }
        }
    }
}