pipeline {
    
    agent any

    tools {
        go '1.18.1'
    }

    environment {
		DOCKERHUB_CREDENTIALS=credentials('docker-hub')
	}
    
    stages {

        stage ('Clone') {
            steps {
                git branch: 'main', url: "https://github.com/22sujata8d/jenkins-ci-demo.git"
            }
        }

        stage("build") {

            steps {
                echo 'building the application...'
                sh 'ls'
                sh script:'''
                    #!/bin/bash
                    cd ./Cart
                    pwd
                    go mod tidy
                    cd ./cmd/server
                    go build .
                '''
            }
        }

        stage("test") {

            steps {
                echo 'testing the application...'
                sh script:'''
                    pwd
                    cd ./Cart
                    go test -v ./...
                '''
            }
        }

        stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

        stage("deploy") {

            steps {
                echo 'deploying the application...'
                sh 'docker push sujata/cart-ms:latest'
            }
        }

        post {
		    always {
			    sh 'docker logout'
		    }
	    }
    }
}